version: '3.3'
services:
  backend:
    image: dto80/se234-lab12:latest
    ports:
      - 8082:8080
    volumes:
      - type: bind
        source: 'data.xlsx'
        target: /data
  frontend:
    image: chawanakorns/lab11-frontend
    ports:
      - 8091:80