version: '3.3'
services:
  backend:
    image: dto80/se234-lab12
    ports:
      - 8082:8080
    volumes:
      - type: bind
        source: 'D:\Chiang Mai University\Year 2\TERM 2\DEV OPS\Lab 10\data\data.xlsx'
        target: /data
  frontend:
    image: chawanakorns/lab10-2-docker-test-new
    ports:
      - 8081:80